# Author: Sagar Singh
# Docker repo: https://hub.docker.com/u/sa40039455

version: '3.3'

services:
    
    elasticsearch:
        image: elasticsearch:2
        volumes:
            - ./esdata/:/usr/share/elasticsearch/data/
        ports: 
            - 9200:9200
            - 9300:9300
    
    logstach:
        image: logstash:7.6.2
        ports:
            - 5044:5044
    
    kibana:
        image: kibana:4.6
        ports: 
            - 5601:5601
